baseURL = "http://worldwind.earth/"
#baseURL = "http://localhost:8383/"
languageCode = "en-us"
title = "WorldWind Earth"
theme = "hugo-darkdoc-custom"
metadataformat = "yaml"
pygmentsUseClasses = true
pygmentsCodefences = true

[params]
    # General information
    author = "Bruce Schubert"
    author_url = "https://github.com/emxsys"
    description = "WorldWind Explorer documentation and unofficial NASA WorldWind resources"
    copyright = "MIT"

    #demo website
    demo_site = "http://explorer.worldwind.earth"

    # Repository
    provider = "GitHub"
    repo_url = "https://github.com/NASAWorldWindResearch/WorldWindExplorer"
    repo_id = "WorldWindExplorer"

    version = "0.2.0"
    favicon = ""

    permalink = "#"

[social]
    github  = "NASAWorldWindResearch"

[[menu.main]]
    name   = "User Guide"
    identifier = "user-guide"
    URL    = "explorer/user/"
    weight = 10

[[menu.main]]
    name   = "Developer Guide"
    identifier = "dev-guide"
    URL    = "explorer/dev/"
    weight = 30

[[menu.main]]
    name   = "WorldWind"
    identifier = "worldwind"
    URL    = "worldwind/"
    weight = 30

